### ISSUE TITLE
InfiniteFluids for 1.8.9

### ISSUE THREAD

**Issue by ghost** [josephcsible/InfiniteFluids#3]
Hi!

Could not find InfiniteFluids for client/server 1.8.9,
so I decided to compile it myself, unfortunately I can not get it to work (cuz i'm dummy).
Tried porting from 1.7.10 as well as from 1.10.2, but still getting errors like:

`[21:15:30] [Client thread/WARN] [infinitefluids/]: Mod infinitefluids has been disabled through configuration`
`[...]`
`[21:15:33] [Client thread/INFO] [STDERR/BuildCraft|Core]: [josephcsible.infinitefluids.InfiniteFluidsClassTransformer:transform:172]: Failed to find the BlockFluidClassic.updateTick method!`

Also it does not appear in "Mods" list.
Could you post InfiniteFluids for 1.8.9, or recommend something.

Thanks in advance,
Alessandro.

**Comment by josephcsible** [comment]
You didn't port it right. Fork my project and upload your changed code to a new branch, and I'll look to try to see what you did wrong. (Dumb question: you did change the code, right? Obviously, just changing the version number and recompiling isn't all it takes to port mods; if it were, you'd never have to wait for mods to be ported.)

**Comment by ghost** [comment]
Ok, got it.
I will do what you told me, a bit later tho.

**Comment by ghost** [comment]
Sorry, I gave up, it's too complicated for me, and not that needed tho.
Command block are always in use.
Bye, closed.
